main:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: Archives
    pageRef: /archives
    weight: 20
    params:
      icon: archive

  - name: Categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories    

  # Example: parent item with dropdown submenu children
  # - name: More
  #   weight: 30
  #   params:
  #     icon: layers

  # - name: Categories
  #   weight: 1
  #   pageRef: /categories
  #   parent: More
  #   params:
  #     icon: categories

  # - name: Series
  #   weight: 3
  #   pageRef: /series
  #   parent: More
  #   params:
  #     icon: bookmark

  # - name: Projects
  #   weight: 4
  #   pageRef: /projects
  #   parent: More
  #   params:
  #     icon: projects

# footer menu
footer:
  - name: " About"
    pageRef: /about
    weight: 20
    params:
      icon: streamline-logos--about-me-logo-block
    
  - name: Tags
    weight: 30
    pageRef: /tags
    params:
      icon: solar--tag-bold

  # - name: Timeline
  #   pageRef: /timeline
  #   weight: 10
  #   params:
  #     icon: chart

  # - name: Resume
  #   pageRef: /resume
  #   weight: 25
  #   params:
  #     icon: file-text

  # - name: RSS Feed
  #   url: /index.xml
  #   weight: 30
  #   params:
  #     icon: rss

# footer social link
social:
  - name: Instagram
    url: https://instagram.com/jundi.mubarok  
    weight: 10
    params:
      icon: mingcute--instagram-fill
  - name: Threads
    url: https://threads.net/@jundi.mubarok
    weight: 20
    params:
      icon: mingcute--threads-fill
  - name: Email
    url: mailto:jundimubarok74@gmail.com
    weight: 30
    params: 
      icon: mingcute--mail-send-fill
  - name: Donate
    url: https://nihbuatjajan.com/jundi/
    weight: 40
    params:
      icon: coffee


