backend:
  name: git-gateway
  repo: jundi14/jundi-blog-narrow
  branch: master
  squash_merges: true #menghapus riwayat commit yang tidak perlu saat melakukan merge
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
publish_mode: editorial_workflow # Aktifkan mode editorial untuk memungkinkan review sebelum publikasi
logo:
  src: https://jundi.web.id/logo-header.png
  show_in_header: true    
media_folder: "static"
public_folder: "" 
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"   # Bagus, garis miring di depan sudah dihapus
    path: "{{slug}}/index"     # Tepat untuk Hugo Page Bundles (tanpa .md)
    preview_path: "posts/{{fields.slug}}"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Karena foldernya sudah unik (pakai slug), nama file cukup index saja melalui properti path.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Categories", name: "categories", widget: "select", 
          options: ["Teknologi", "Blogging", "Coretan"] } 
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    layout: "about" # Gunakan layout khusus untuk halaman about
    folder: "content/about"   # Bagus, garis miring di depan sudah dihapus
    create: false
    path: "index" # Memastikan CMS mengedit file content/about/index.md
    media_folder: "" # Kosongkan agar gambar diunggah ke folder yang sama (content/about)
    public_folder: "" # Kosongkan agar di dalam Markdown tertulis nama file gambarnya saja (misal: "foto.jpg")
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }