backend:
  name: git-gateway
  repo: jundi14/jundi-blog-narrow
  branch: master 
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"   # Bagus, garis miring di depan sudah dihapus
    path: "{{slug}}/index"     # Tepat untuk Hugo Page Bundles (tanpa .md)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Karena foldernya sudah unik (pakai slug), nama file cukup index saja melalui properti path.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Categories", name: "categories", widget: "list" } # Diubah ke list agar menghasilkan ["Teknologi"]
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }