backend:
  name: git-gateway
  repo: jundi14/jundi-blog-narrow
  branch: master 
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"   # Bagus, garis miring di depan sudah dihapus
    path: "{{slug}}/index"     # Tepat untuk Hugo Page Bundles (tanpa .md)
    preview_path: "/posts/{{slug}}" # Tambahkan ini untuk preview yang benar
    preview_path_date_field: "date" # Tambahkan ini untuk memastikan tanggal digunakan dalam URL preview
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Karena foldernya sudah unik (pakai slug), nama file cukup index saja melalui properti path.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Categories", name: "categories", widget: "list" } # Diubah ke list agar menghasilkan ["Teknologi"]
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Featured Image", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    layout: "about" # Gunakan layout khusus untuk halaman about
    folder: "content/about"   # Bagus, garis miring di depan sudah dihapus
    create: false
    path: "index" # Memastikan CMS mengedit file content/about/index.md
    media_folder: "" # Kosongkan agar gambar diunggah ke folder yang sama (content/about)
    public_folder: "" # Kosongkan agar di dalam Markdown tertulis nama file gambarnya saja (misal: "foto.jpg")
    slug: "{{slug}}" # Karena foldernya sudah unik (pakai slug), nama file cukup index saja melalui properti path.
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }